fixtures:
  forge_modules:
    stdlib: "puppetlabs/stdlib"
    vcsrepo: "puppetlabs/vcsrepo"
    concat:
      repo: "puppetlabs/concat"
      ref: "2.2.1"
    apt:
      repo: "puppetlabs/apt"
      ref: "2.4.0"
    zypprepo: "puppet/zypprepo"
  symlinks:
    icingaweb2: "#{source_dir}"
